# Copyright 2025 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

name: ci

on:
  push:
    branches:
      - 'v*-dev'
      - master
  pull_request:
  workflow_dispatch:

jobs:
  verilator-elaboration:
    name: Verilator Elaboration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Free disk space
        uses: ./.github/actions/free-space
      - name: Run Verilator elaboration
        uses: ./.github/actions/oseda-cmd
        with:
          cmd: "make vlt-elab"

  verible-lint:
    name: Verible Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Free disk space
        uses: ./.github/actions/free-space
      - name: Run Verible lint
        uses: ./.github/actions/oseda-cmd
        with:
          cmd: ".github/scripts/run_verible_lint.sh"
